name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install deps
        run: pnpm install

      - name: Build Storybook
        run: pnpm run build-storybook

      - name: Build and deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./storybook-static
